# Generated by Django 4.0.6 on 2022-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippleswebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='password',
        ),
        migrations.AddField(
            model_name='sample',
            name='email',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
