# Generated by Django 4.0.6 on 2022-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippleswebsite', '0002_remove_sample_password_sample_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nte2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Nte3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Te1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Te2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Te3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sample',
            new_name='Nte1',
        ),
    ]
